trigger:
- master

pr:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'npm install'

- script: |
    ng test
  displayName: 'ng test'

- script: |
    ng build --prod --base-href https://staticauthtest.z6.web.core.windows.net/
  displayName: 'ng build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: 'dist'
